### ISSUE TITLE
support custom cacheDir

### ISSUE THREAD

**Issue by smelukov** [zhangHongEn/module-federation-vite#2]
Can't use shared packages

```js
import { defineConfig } from 'vite'
import mf from "module-federation-vite"

export default defineConfig({
  plugins: [
    mf({
      shared: {
        foo: {
            singleton: true
        },
      },
    }),
  ],
});
```

```js
import * as foo from 'foo';

console.log(foo); // {default: {}} for any package in shared-section
```

foo should have some other properties

**Comment by zhangHongEn** [comment]
Is "foo" an npm package?

**Comment by smelukov** [comment]
Yep
For example, here is a chunk content for react as a shared:
```js
import {empty_default} from "/@fs/path/to/node_modules/.vite/apps/admin/deps/chunk-PYBZOKV4.js?v=5d5a460f";
import "/@fs/path/toinode_modules/.vite/apps/admin/deps/chunk-GFT2G5UO.js?v=5d5a460f";
export {empty_default as default};
```

```js
import * as react from 'react';

console.log(react); // {default: {}} 
```

**Comment by zhangHongEn** [comment]
> Yep For example, here is a chunk content for react as a shared:
> 
> ```js
> import {empty_default} from "/@fs/path/to/node_modules/.vite/apps/admin/deps/chunk-PYBZOKV4.js?v=5d5a460f";
> import "/@fs/path/toinode_modules/.vite/apps/admin/deps/chunk-GFT2G5UO.js?v=5d5a460f";
> export {empty_default as default};
> ```
> 
> ```js
> import * as react from 'react';
> 
> console.log(react); // {default: {}} 
> ```

I need a reproducible demo. I can't reproduce it in the demo of the current repository or in my own project. I'm not sure if it's affected by the vite version.

**Comment by zhangHongEn** [comment]
I think I know the problem. Could you please send me the dependency version of npm ls or pnpm ls so I can check it? Or upgrade the vite version to see if it can be solved?

**Comment by zhangHongEn** [comment]
Probably the path of the proxy resource is not matched here. The URL rules may be different in different vite versions or devices.
https://github.com/zhangHongEn/module-federation-vite/blob/e848e822687c850f76cca837714350968bf6c0f0/packages/module-federation-vite/src/index.js#L202C14-L202C33

**Comment by smelukov** [comment]
We're using custom cache dir for out monorepo packages
The the is reproducing when custom cache dir is specifed (e.g: `cacheDir: '../../node_modules/.vite/apps/admin'`)

**Comment by zhangHongEn** [comment]
> We're using custom cache dir for out monorepo packages The the is reproducing when custom cache dir is specifed (e.g: `cacheDir: '../../node_modules/.vite/apps/admin'`)

This is the problem, I will add compatibility with cacheDir
