### ISSUE TITLE
Cannot read properties of undefined (reading 'shareConfig')

### ISSUE THREAD

**Issue by smelukov** [zhangHongEn/module-federation-vite#3]
**vite.config.ts:**
```ts
import { defineConfig } from 'vite'
import mf from "module-federation-vite"

export default defineConfig({
    plugins: [
        mf({
            filename:'foo-mf.js',
            name: 'foo',
            remotes:{},
            exposes:{},
        }),
    ],
});
```

**main.ts:**
```ts
import {Parser} from '@json2csv/plainjs';

console.log(Parser)
```

This example produces the following error:
```
[plugin:module-federation-vite] Cannot read properties of undefined (reading 'shareConfig')
/Users/smelukov/example/node_modules/.vite/deps/@json2csv_plainjs.js
```

**Comment by zhangHongEn** [comment]
Yes, I will deal with it together now

**Comment by smelukov** [comment]
Thanks for quick replies!

**Comment by zhangHongEn** [comment]
#2 #3
The fix is ​​complete, npm 1.0.6 has been released

**Comment by smelukov** [comment]
Another error:
`Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@json2csv_plainjs.js?v=710728b9' does not provide an export named 'Parser' (at main.ts:1:10)`

You can use example from the first message

```
"module-federation-vite": "1.0.6",
"vite": "5.3.5"
```

**Comment by smelukov** [comment]
Should I create a separated issue for that error?

**Comment by zhangHongEn** [comment]
I'm on my way home from work, and I can fix it when I get home

---- Replied Message ----
| From | Sergey ***@***.***> |
| Date | 07/31/2024 21:43 |
| To | zhangHongEn/module-federation-vite ***@***.***> |
| Cc | zhn ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [zhangHongEn/module-federation-vite] Cannot read properties of undefined (reading 'shareConfig') (Issue #3) |

Should I create a separated issue for that error?

**Comment by smelukov** [comment]
Thanks!

**Comment by zhangHongEn** [comment]
1.0.7 released
